//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quote.QuoteWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuoteWebService.serviceSoap")]
    public interface serviceSoap {
        
        // CODEGEN: Generating message contract since element name rbShape from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMeasurementSize", ReplyAction="*")]
        Quote.QuoteWebService.getMeasurementSizeResponse getMeasurementSize(Quote.QuoteWebService.getMeasurementSizeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMeasurementSizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMeasurementSize", Namespace="http://tempuri.org/", Order=0)]
        public Quote.QuoteWebService.getMeasurementSizeRequestBody Body;
        
        public getMeasurementSizeRequest() {
        }
        
        public getMeasurementSizeRequest(Quote.QuoteWebService.getMeasurementSizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMeasurementSizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rbShape;
        
        public getMeasurementSizeRequestBody() {
        }
        
        public getMeasurementSizeRequestBody(string rbShape) {
            this.rbShape = rbShape;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMeasurementSizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMeasurementSizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quote.QuoteWebService.getMeasurementSizeResponseBody Body;
        
        public getMeasurementSizeResponse() {
        }
        
        public getMeasurementSizeResponse(Quote.QuoteWebService.getMeasurementSizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMeasurementSizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getMeasurementSizeResult;
        
        public getMeasurementSizeResponseBody() {
        }
        
        public getMeasurementSizeResponseBody(int getMeasurementSizeResult) {
            this.getMeasurementSizeResult = getMeasurementSizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : Quote.QuoteWebService.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<Quote.QuoteWebService.serviceSoap>, Quote.QuoteWebService.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quote.QuoteWebService.getMeasurementSizeResponse Quote.QuoteWebService.serviceSoap.getMeasurementSize(Quote.QuoteWebService.getMeasurementSizeRequest request) {
            return base.Channel.getMeasurementSize(request);
        }
        
        public int getMeasurementSize(string rbShape) {
            Quote.QuoteWebService.getMeasurementSizeRequest inValue = new Quote.QuoteWebService.getMeasurementSizeRequest();
            inValue.Body = new Quote.QuoteWebService.getMeasurementSizeRequestBody();
            inValue.Body.rbShape = rbShape;
            Quote.QuoteWebService.getMeasurementSizeResponse retVal = ((Quote.QuoteWebService.serviceSoap)(this)).getMeasurementSize(inValue);
            return retVal.Body.getMeasurementSizeResult;
        }
    }
}
